### ISSUE TITLE
Refactoring plan (Hello world!)

### ISSUE THREAD

**Issue by nmansard** [loco-3d/ndcurves#1]
This repo should become the master repo for the former hpp-spline project. We are expecting a significant refactoring of the code. I list the main expected actions here and will open one issue for each.
1. Naming refactoring: change names, namespace and repo name
2. Refactor python bindings
3. Add some new curves
4. Add a proper serialization
5. Add a mathematics documentation describing each curve paramatrization
6. Introduce a generic conversion mechanism
7. Introduce systematic unittest using the serialization.
A engineer will work full time on these tasks from next monday.

**Comment by JasonChmn** [comment]
Changes done :
1. Change name from hpp_spline to curves / change namespace from curve to curves
2. Python bindings done for all classes/functions
3. Cubic Hermite Curve and Piecewise curves added ( Sinus and other curves may need to be added later )
4. All curves can be serialized with boost::serialization
5. Documentation done (Need to be checked before sharing)
6. Conversion between curves or piecewise curve containing curves of degree 3 or less implemented
