### ISSUE TITLE
Divergence between master and devel?

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/ndcurves#15]
I just noticed that the master branch appears to be more current than the devel branch. However, there are a lot more commits on the devel that haven't been merged:

![image](https://user-images.githubusercontent.com/1664508/70712515-dc708a80-1cdb-11ea-95fa-68fb1a23ea03.png)

What is the status of the two branches?

**Comment by stonneau** [comment]
Hi, in fact we are waiting for @nim65s to finish a release on the gepgitlab version of curves, those branches should be updated accordingly afterwards.
Sorry about this.

Thanks a lot for your pull request, I will wait for the release to update your fixes to the latest version and merge

**Comment by nim65s** [comment]
I looked at that yesterday, and the CI was not really happy: https://gepgitlab.laas.fr/loco-3d/curves/pipelines/7590

I'll have to fix this, or at least understand what's happening, first.

**Comment by pFernbach** [comment]
This CI errors are related to this issue : https://gepgitlab.laas.fr/loco-3d/curves/issues/22

**Comment by pFernbach** [comment]
The "most recent" changes in the master branch are just doc/Readme updates. I should have merged them in devel after but I forgot. 

All the new features are in devel, and there isn't any _code_ divergence between master and devel.
