### ISSUE TITLE
Change lib names and namespaces

### ISSUE THREAD

**Issue by nmansard** [loco-3d/ndcurves#2]
We want to take this lib out of the hpp namespace, and rename it for the more generic "curve" as spline is only one of the implemented curve.

**Comment by JasonChmn** [comment]
Name as been changed from hpp-spline to curves.

**Comment by florent-lamiraux** [comment]
Sorry to react so lately, but I think that the name "curves" is too generic and may prevent us to make this package broadly used outside of our team. I understand the wish to remove prefix "hpp", but I would replace it by another prefix "gepetto", "loco3d" or whatever you like.

**Comment by wxmerkt** [comment]
curves is also the name of a package by ASL (https://github.com/ethz-asl/curves) - as such I am locally usually "loco3d_curves" to avoid conflicts with Anymal code

**Comment by stonneau** [comment]
Ok. How urgent is the issue ?

**Comment by florent-lamiraux** [comment]
It is not really an issue, only a comment.

**Comment by wxmerkt** [comment]
Not urgent for me, I have locally renamed the library and separate the workspaces - so a comment for future consideration

**Comment by stonneau** [comment]
@pFernbach @JasonChmn  any opinion? The motivation for removing hpp was that the package should not be limited to hpp software but maybe we went too far.

I understand the issue but the impact of this change in all the libraries that use curve is quite important, especially after @pFernbach spent the last few weeks propagating the library in many Laas packages.

**Comment by pFernbach** [comment]
It would be adding a prefix to the name and adding a top level namespace everywhere ? 
The refactoring of the code should be quite easy, but it will add work for the next releases of the impacted packages.

**Comment by wxmerkt** [comment]
We are seeing configuration conflicts when using with Anymal & other ROS software as the name `curves` is used by https://github.com/ethz-asl/curves - i.e. `find_package(curves REQUIRED)` can pick up the wrong one. We haven't seen a compile or runtime conflict yet but it shows that Anybotics code tries to pick up loco-3d curves.

**Comment by wxmerkt** [comment]
Any thoughts on a potential name change? We'd like to eliminate potential runtime clashes when deploying the MPC on Anymal

**Comment by stonneau** [comment]
Ok we'll change the namespace. This is not really in my backlog however and I think I m the only one available for this.
I need to find a name also. Any ideas? By default I ll just call it loco3D-curves.

Can you give me a deadline for this to be done ?

**Comment by wxmerkt** [comment]
I have no preference on namespace, `loco3d_curves` works fine. Does within the next two weeks work?

**Comment by stonneau** [comment]
Well, it depends by what is involved in the next two weeks.
Having a branch where the change has been done is doable,
Propagating the changes to the depending libraries and will take longer.

@nim65s would it be possible to release a new library from a branch / fork while the change of name is not propagated?

**Comment by wxmerkt** [comment]
We can work off source so it does not require a release since I expect such a namespace change to require a major version upgrade etc.

**Comment by stonneau** [comment]
Yeah ok, so then it should be done shortly (I ll get to it as soon as an open PR is merged)

**Comment by wxmerkt** [comment]
Thank you very much, highly appreciated :-)

**Comment by stonneau** [comment]
I have done the renaming locally but I am not sure yet of the name. I ll update early next week.

**Comment by stonneau** [comment]
I think I ll rename the library NDcurves for n dimensional.
I did not want it to be attached to locomotion as it's more generic than that.
If no one objects I ll push the branch

**Comment by florent-lamiraux** [comment]
I would avoid capital letters in file names. Why not nd-curves ?

**Comment by stonneau** [comment]
ok

**Comment by stonneau** [comment]
See https://github.com/loco-3d/curves/tree/nd_curves @wxmerkt

**Comment by wxmerkt** [comment]
Thank you @stonneau :-)

**Comment by stonneau** [comment]
So the final name is ndcurves
