### ISSUE TITLE
Replace assert with std::throw_exception

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/ndcurves#28]
asserts are silent - so we won't know if the user-specified input is wrong

**Comment by stonneau** [comment]
Hi, this is part of an unresolved discussion between me and former gepetto members. Ideally all asserts will be removed... when I have time

**Comment by stonneau** [comment]
Thanks a lot for your work. If you want to make a pull request, I ll update your commits to simultaneously address another issue related to numerical approximations

**Comment by wxmerkt** [comment]
Pull request is here: #29

**Comment by pFernbach** [comment]
Solved by https://github.com/loco-3d/curves/pull/29
