### ISSUE TITLE
Add some new curve parametrization

### ISSUE THREAD

**Issue by nmansard** [loco-3d/ndcurves#4]
We need at least
* bicubic hermitian splines interpolating position-velocity sampling (to be taken from https://gepgitlab.laas.fr/loco-3d/multicontact-api/)
* piecewise constant
Other curves should be introduced from https://github.com/stack-of-tasks/parametric-curves.

**Comment by JasonChmn** [comment]
1. Cubic Hermite spline has been added to curves.
2. Piecewise curve has been added to curves which can contain any curve inheriting from curve_abc. 
New curves may be added if needed.
