### ISSUE TITLE
cross / dot product computation for curves of dimension 3

### ISSUE THREAD

**Issue by stonneau** [loco-3d/ndcurves#51]
I am wondering whether it is relevant to the cross product operation operation to the curves library.
It is well defined for curves of dimension 3, and are overall useful for the problems we are considering in robotics.

However this might be considered as a specialisation of the library and it will introduce more differences
between 3d types and others.

On the other end the dot product is well defined for all curves, no matter what dimension is considered, but I have not seen a use for it so far. Any thoughts ?

**Comment by pFernbach** [comment]
There is already special cases for the curves of dimension 3, and the python binding is different for this curves to allow this. 
It doesn't bother me to add more specialization like this. 

However I am not sure about the best way to implement this: just checking the dimension at runtime and throwing an error if it's not 3 doesn't seems nice, and using template specialization just for this method seems overly complex.

**Comment by stonneau** [comment]
The problem is a bit tricky, but in this very special case I am okay with assuming the user knows what he is doing and let Eigen fails if the cross product is called

**Comment by pFernbach** [comment]
If we are going this way, I think it would be a lot better to raise the error in Curves before calling Eigen. Eigen errors are always kind of hard to track and understand.

**Comment by stonneau** [comment]
Sure, why not. I ll make a pr soon on cross product for polynomials and Bezier variables

**Comment by stonneau** [comment]
See https://github.com/loco-3d/curves/pull/52
