### ISSUE TITLE
Pickable curve_constraints objects

### ISSUE THREAD

**Issue by cmastalli** [loco-3d/ndcurves#55]
Hi guys,

I would like to `deepcopy` an Python class that contains `curve_constraints` object.
Unfortunately, this is not enable at the moment.
I believe it is useful to make them pickable.

Below you can see the message error
```bash
/usr/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
    161     copier = _deepcopy_dispatch.get(cls)
    162     if copier:
--> 163         y = copier(x, memo)
    164     else:
    165         try:
...
RuntimeError: Pickling of "curves.curves.curve_constraints" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
```

Carlos

**Comment by pFernbach** [comment]
Hello, I am not sure to understand why you need pickle for a deep copy, but anyway I added this feature with https://github.com/loco-3d/curves/pull/56

**Comment by cmastalli** [comment]
Thanks @pFernbach :)
I am not aware of the `deepcopy` details neighter.

Do you want me to check it?

**Comment by pFernbach** [comment]
No, it doesn't really matter I guess. It was just curiosity.

**Comment by stonneau** [comment]
can we close the issue ?

**Comment by pFernbach** [comment]
Yes.

**Comment by cmastalli** [comment]
Guys, it would be nice if you can produce a new release ;)
