### ISSUE TITLE
Standardization of parameter conversion

### ISSUE THREAD

**Issue by nmansard** [loco-3d/ndcurves#7]
Conversion stands for converting one curve parametrization to another one. This might be exact (for example passing from a Bezier to polynomial monomes with the same polynomial degrees) or approximate following an optimal principle (for example, finding the closest piecewise constant approximating a Bezier). 

This task consists in 2 parts:
1. first introduce a standard mechanism to implement the conversion, and cast the existing conversion routines to this standard.
2. implement a default conversion from any class A to piecewise polynomials and from standard polynomials to class B.

**Comment by JasonChmn** [comment]
1. Conversion functions from and to bezier, polynomial and cubic hermite curves of degree 3 or less have been added.
2. Piecewise curve containing bezier, polynomial or cubic hermite of degree 3 can be converted directly to a piecewise curve containing one these types of curves.
